
name: inventa
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.9.7
  - numpy==1.20.3
  - pip==21.1.3
  - pandas==1.4.0
  - pip:
    - scikit_bio==0.5.6
    - scikit_learn==1.0.2
    - matplotlib==3.4.3
    - plotly==4.14.3
    - ipywidgets==7.6.5
    
