
name: inventa
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.9.7
  - numpy==1.20.3
  - pip==21.1.3
  - pandas==1.4.0
  - pip:
    - ipykernel<6.4
    - jupyter_client<7
    - scikit_bio==0.5.6
    - scikit_learn==1.0.2
    - matplotlib==3.5.1
    - plotly==4.14.3
    - ipywidgets==7.6.5
    - cimcb_lite==1.0.2
    - lineup_widget==4.0.0
    - jupyter_contrib_nbextensions
