
name: inventa
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.9.7
  - numpy==1.20.3
  - pip==21.1.3
  - pandas==1.4.0
  - rdkit::rdkit
  - molvs
  - pip:
    - ipykernel
    - jupyter_client
    - scikit_bio
    - scikit_learn
    - matplotlib
    - plotly
    - ipywidgets
    - cimcb_lite
    - lineup_widget
    - jupyter_contrib_nbextensions
