
name: inventa
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.9.*
  - numpy==1.1.*
  - pip==21.1.*
  - pandas==1.4.*
  - rdkit::rdkit
  - molvs
  - pip:
    - ipykernel
    - jupyter_client
    - scikit_bio
    - scikit_learn
    - matplotlib
    - plotly
    - ipywidgets
    - cimcb_lite
    - lineup_widget
    - jupyter_contrib_nbextensions
