# default.yaml

---
# parameters

Feature_component:
  - calculate_FC: True #FC will be calculated
  - min_specificity: False #minimun feature specificity to consider
  - only_feature_specificity: False #True if annotations should be ignore and the FC should be calculated based on the features specificity. If False it will compute both The Sample specifity adn the FC
  - only_gnps_annotations: True #only the annotations from gpns will be considered
  - only_ms2_annotations: False  #False to considere both, MS1 & MS2 annotations, False will only considerer MS2 annotations
  - annotation_preference: 0  #Only Annotated nodes: '1' 
                              #Only Not annotated: '0'

Literature_component:
  - calculate_LC: True #LC will be calculated
  - max_comp_reported: 40 #more than this value, the plant is considered no interesting LC =0
  - min_comp_reported: 10 #less than this value, the plant is consireded very interesintg LC =1
                          #a sample with x between both values gets a LC=0.5

Class_component:
  - calculate_CC: True #CC will be calculated

Similarity_component:
  - calculate_SC: True #SC will be calculated

paths:
  - metadata_filename: '../data/Celastraceae_Set_metadata_pos.tsv' # The path were you want your folder to be placed
  - quantitative_data_filename: ../data/Celastraceae_Set_metadata_pos.tsv # The path were you want your GNPS job folder to be placed
  - tima_results_filename: ../data/Celastraceae_pos_spectral_match_results_repond.tsv #ISDB_annot_LP_plantfungi_set # The name you want to give to your project, output resulst in data_out/project_name
  - vectorized_data_filename: ../data/Celastraceae_memomatrix.csv # the path for your output to be stored in
  - canopus_npc_summary_filename: ../data/canopus_npc_summary.tsv  # Path to your spectral library file
  - sirius_annotations_filename: ../data/canopus_npc_summary.tsv # Path to the metadata of the spectral file
  - LotusDB_filename: ../data_loc/LotusDB_inhouse_metadata.csv