title: "INVENTA"
description: "Workflow of prioritization of natural extracts for chemical originality discovery"
logo: /assets/img/logo.png
subtitle: "Version 1.0"
name: Luis Quiros-Guerrero

repository: "luigiquiros/inventa"

#building 
theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - installation.md
  - configuration-options.md
  - workflow.md
  - getting-started.md
