site_name: Inventa
site_author: Luis Quiros-Guerrero
repo_url: https://luigiquiros.github.io/inventa/
repo_name: 'Github'
    
nav:
    - Home: "index.md"
    - Installation: "installation.md"
    
    
    - User-guide:
        - 0. Workflow: "workflow.md"
        - 1. Getting started: 'getting-started.md'
        - 2. Configuration: 'confguration_options.md'

        
#Theming
theme: #jekyll-theme-cayman
    name: mkdocs #jekyll-theme-cayman
    #logo: docs/assets/logo.png
    #favicon: 'assets/images/favicon.ico'
