# Site settings
title: Inventa
author: Luis Quiros-Guerrero   
email: luis.guerrero@unige.ch
github: https://github.com/luigiquiros/
description: "Workflow of prioritization of natural extracts for chemical originality discovery"


# Build settings 
theme: jekyll/minima
markdown: kramdown
#nav:
 #   - Home: index.md
 #   - Installation: installation.md 
 #   - User-guide:
 #       - 0. Workflow: workflow.md
 #       - 1. Getting started: getting-started.md
 #       - 2. Configuration: confguration_options.md
