title: "INVENTA"
description: "Workflow of prioritization of natural extracts for chemical originality discovery"
subtitle: "Version 1.0"
name: Luis Quiros-Guerrero

url: "https://luigiquiros.github.io"
baseurl: "/inventa/docs"
repository: "luigiquiros/inventa"

#building

theme: minimal-jekyll #minimal-mistakes-jekyll
#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#teaser: /assets/images/graphical_abstract.png
#header:
#  teaser: /assets/images/my-awesome-post-teaser.jpg

#logo: "/assets/images/logo.png"

#footer:
#  links:
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
 #     url: "https://github.com/luigiquiros"

#defaults:
  # _pages
#  - scope:
#      path: ""
#      type: pages
#    values:
 #     layout: single
  # _foo
#  - scope:
#      path: ""
#      type: foo
 #   values:
 #     layout: single
      
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
