title: "Inventa"
description: " a computational tool to discover chemical novelty in natural  extracts libraries"
logo: /assets/img/logo.png


subtitle: "Version 1.0.0"
name: Luis Quiros-Guerrero
email: luis.guerrero@unige.ch


repository: "luigiquiros/inventa"

#building 
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - installation.md
  - configuration-options.md
  - workflow.md
  - getting-started.md
